### ISSUE TITLE
Update to follow Guard 2.0 changes

### ISSUE THREAD

**Issue by ezekg** [makevoid/guard-concat#7]
Getting deprecation warnings. More info is [here](https://github.com/guard/guard/wiki/Upgrading-to-Guard-2.0#changes-in-guardguard).

```
09:37:50 - WARN - Starting with Guard 2.0, Guard::Concat should inherit from Guard::Plugin
> [#] instead of Guard::Guard.
> [#] Please note that the constructor signature has changed from
> [#] Guard::Guard#initialize(watchers = [], options = {}) to
> [#] Guard::Plugin#initialize(options = {}).
> [#] For more information on how to upgrade for Guard 2.0, please head over
> [#] to: https://github.com/guard/guard/wiki/Upgrading-to-Guard-2.0#changes-in-guardguard
> [#]
> [#] Deprecation backtrace: /Library/Ruby/Gems/2.0.0/gems/guard-2.8.2/lib/guard/ui.rb:107:in `deprecation'
> [#] 	 >/Library/Ruby/Gems/2.0.0/gems/guard-2.8.2/lib/guard/guard.rb:94:in `initialize'
> [#] 	 >/Library/Ruby/Gems/2.0.0/gems/guard-concat-0.0.3/lib/guard/concat.rb:17:in `initialize'
```

**Comment by makevoid** [comment]
fixed with https://github.com/makevoid/guard-concat/pull/8 - thanks!
